---
name: Publish Radarr

on:
  repository_dispatch:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/*"
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  lint_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Hadolint
        uses: brpaz/hadolint-action@v1.1.0
        continue-on-error: true

  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish
        id: vars
        run: |
          set -e

          ALPINE_VERSION=3.12
          IMAGE_NAME=failfr8er/radarr
          RADARR_RAW=$(curl -H "Accept: application/vnd.github.v3+json" -s https://api.github.com/repos/radarr/radarr/releases/latest)
          RADARR_VERSION=$(echo "${RADARR_RAW}" | jq -r '.tag_name')
          RADARR_ASSET=$(echo "${RADARR_RAW}" | jq -r '.assets[] | select(.name | endswith(".linux-musl-core-x64.tar.gz")).browser_download_url')

          echo ::set-output name=RADARR_VERSION::${RADARR_VERSION}

          wget "${RADARR_ASSET}"

          docker buildx build \
            --file Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag ${IMAGE_NAME}:latest \
            --tag ${IMAGE_NAME}:3 \
            --tag ${IMAGE_NAME}:${RADARR_VERSION} \
            --push \
            --build-arg ALPINE_VERSION=${ALPINE_VERSION} \
            --build-arg RADARR_VERSION="${RADARR_VERSION:1}" \
            --platform=linux/amd64 \
            .

      - name: Container image scan
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: "failfr8er/radarr:${{ steps.vars.outputs.RADARR_VERSION }}"
